import { Inter } from 'next/font/google'
import './css/globals.css'
import { ClerkProvider, ClerkLoaded, ClerkLoading } from '@clerk/nextjs'
import Navbar from '@/components/Navbar'
import { dark } from '@clerk/themes'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang='en'>
        <head>
          {/* Add Font Awesome CDN link here */}
          <link
            rel='stylesheet'
            href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css'
            integrity='sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=='
            crossOrigin='anonymous'
            referrerPolicy='no-referrer'
          />
        </head>
        <body className={inter.className}>
          <ClerkLoading>
            <div className='flex items-center justify-center h-screen text-2xl'>
              LOADING...
            </div>
          </ClerkLoading>
          <ClerkLoaded>
            <div className=''>
              <div className=''>
                <Navbar />
                {children}
              </div>
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  )
}
